import pandas as pd

COMPANY_PRODUCTS: dict[str, list[str]] = {
    # ── Technology ──────────────────────────────────────────────────────────────
    "Arcoven Systems": [
        "Arcoven Enterprise Suite",
        "Arcoven Identity Manager",
        "Arcoven Workflow Engine",
        "Arcoven API Gateway",
        "Arcoven Data Sync",
        "Arcoven Audit Logger",
        "Arcoven Role Provisioner",
    ],
    "Nexlith AI": [
        "Nexlith Predict",
        "Nexlith Vision API",
        "Nexlith NLP Toolkit",
        "Nexlith AutoLabel",
        "Nexlith Model Hub",
        "Nexlith Inference Engine",
        "Nexlith Drift Monitor",
        "Nexlith Training Cluster",
    ],
    "Qubit Foundry": [
        "Qubit Foundry QPU Simulator",
        "Qubit Foundry Noise Analyzer",
        "Qubit Foundry Circuit Composer",
        "Qubit Foundry Error Correction Suite",
        "Qubit Foundry Quantum SDK",
        "Qubit Foundry Cryogenic Controller",
    ],
    "Solvera Labs": [
        "Solvera Research Platform",
        "Solvera Experiment Tracker",
        "Solvera Data Annotator",
        "Solvera Hypothesis Engine",
        "Solvera Lab Notebook",
        "Solvera Reproducibility Suite",
        "Solvera Collaboration Hub",
    ],
    "Vantiq Cloud": [
        "Vantiq Cloud Core",
        "Vantiq Edge Runtime",
        "Vantiq Event Mesh",
        "Vantiq App Builder",
        "Vantiq Real-Time Analytics",
        "Vantiq IoT Connector",
        "Vantiq Orchestration Engine",
        "Vantiq Cost Monitor",
    ],
    "Creston Data": [
        "Creston DataWarehouse",
        "Creston Pipeline Builder",
        "Creston Query Studio",
        "Creston Data Catalog",
        "Creston Lineage Tracker",
        "Creston Schema Registry",
        "Creston Stream Processor",
    ],
    "Novalume Inc.": [
        "Novalume Smart Panel",
        "Novalume Edge Node",
        "Novalume Sensor Array",
        "Novalume Display Driver",
        "Novalume Firmware OTA",
        "Novalume Power Manager",
    ],
    "Phalanx Security": [
        "Phalanx Threat Shield",
        "Phalanx Endpoint Guard",
        "Phalanx Zero-Trust Gateway",
        "Phalanx SOC Dashboard",
        "Phalanx Vulnerability Scanner",
        "Phalanx Identity Vault",
        "Phalanx Incident Responder",
        "Phalanx Pen-Test Automation",
    ],
    "Runecode Corp.": [
        "Runecode IDE Extension",
        "Runecode CI Runner",
        "Runecode Code Review Bot",
        "Runecode Dependency Auditor",
        "Runecode Test Generator",
        "Runecode Deploy Agent",
        "Runecode Metrics Dash",
    ],
    "Tessact Software": [
        "Tessact Project Manager",
        "Tessact Kanban Board",
        "Tessact Time Tracker",
        "Tessact Resource Planner",
        "Tessact Release Notes Generator",
        "Tessact Roadmap Studio",
    ],
    "Lyrion Networks": [
        "Lyrion SD-WAN",
        "Lyrion Network Fabric",
        "Lyrion Traffic Optimizer",
        "Lyrion BGP Controller",
        "Lyrion Network Analytics",
        "Lyrion Cloud Connect",
        "Lyrion QoS Manager",
        "Lyrion Redundancy Planner",
    ],
    "Obsidia Tech": [
        "Obsidia Storage Array",
        "Obsidia Backup Vault",
        "Obsidia Dedup Engine",
        "Obsidia Snapshot Manager",
        "Obsidia Cold Archive",
        "Obsidia Encryption Layer",
        "Obsidia Restore Console",
    ],
    "Pulsar Compute": [
        "Pulsar Bare Metal Instances",
        "Pulsar GPU Cluster",
        "Pulsar High-Memory VMs",
        "Pulsar Spot Compute",
        "Pulsar Autoscaler",
        "Pulsar Workload Scheduler",
        "Pulsar Billing Analytics",
    ],
    "Driftware": [
        "Driftware Config Drift Detector",
        "Driftware IaC Validator",
        "Driftware Policy Enforcer",
        "Driftware State Snapshotter",
        "Driftware Remediation Engine",
        "Driftware Compliance Reporter",
    ],
    "Intrium Digital": [
        "Intrium Digital Twin Platform",
        "Intrium Process Mapper",
        "Intrium Automation Studio",
        "Intrium Change Management Suite",
        "Intrium Stakeholder Portal",
        "Intrium ROI Tracker",
        "Intrium Integration Hub",
    ],
    "Coda Robotics": [
        "Coda Mobile Manipulator",
        "Coda Autonomous Forklift",
        "Coda Vision System",
        "Coda Fleet Controller",
        "Coda Simulation Suite",
        "Coda Gripper Module",
        "Coda Safety Sensor Pack",
        "Coda Remote Ops Console",
    ],
    "Veratex AI": [
        "Veratex Document Classifier",
        "Veratex Extraction Engine",
        "Veratex Conversational Agent",
        "Veratex Sentiment Analyzer",
        "Veratex Knowledge Graph Builder",
        "Veratex Fine-Tune Studio",
        "Veratex Evaluation Bench",
    ],
    "Spectra Logic": [
        "Spectra Tape Library",
        "Spectra Object Storage",
        "Spectra Data Migration Kit",
        "Spectra Tiered Storage Manager",
        "Spectra Archive Indexer",
        "Spectra Compliance Vault",
    ],
    "Kinetica Systems": [
        "Kinetica GPU Database",
        "Kinetica Stream Ingestor",
        "Kinetica Geospatial Analyzer",
        "Kinetica Dashboard Builder",
        "Kinetica Anomaly Detector",
        "Kinetica Vector Search",
        "Kinetica Time-Series Engine",
    ],
    "Zephyr Compute": [
        "Zephyr Serverless Functions",
        "Zephyr Container Registry",
        "Zephyr Kubernetes Service",
        "Zephyr CDN",
        "Zephyr Object Store",
        "Zephyr Dev Sandbox",
        "Zephyr Cost Optimizer",
        "Zephyr Observability Suite",
    ],
    "Axiom DevOps": [
        "Axiom Pipeline Orchestrator",
        "Axiom Secret Manager",
        "Axiom Release Gate",
        "Axiom Feature Flags",
        "Axiom Deployment Tracker",
        "Axiom On-Call Scheduler",
        "Axiom Post-Mortem Builder",
    ],
    "Lumos Platform": [
        "Lumos Access Review",
        "Lumos Permission Discovery",
        "Lumos App Catalog",
        "Lumos Provisioning Engine",
        "Lumos Offboarding Automator",
        "Lumos SaaS Spend Tracker",
    ],
    "Orbis Analytics": [
        "Orbis BI Studio",
        "Orbis Predictive Models",
        "Orbis Data Blender",
        "Orbis Report Scheduler",
        "Orbis Cohort Analyzer",
        "Orbis Funnel Explorer",
        "Orbis Embedded Analytics SDK",
    ],
    "Sable AI": [
        "Sable Recommendation Engine",
        "Sable Personalization API",
        "Sable A/B Test Manager",
        "Sable Churn Predictor",
        "Sable Lead Scorer",
        "Sable Segmentation Engine",
        "Sable Attribution Model",
    ],
    "Trident Software": [
        "Trident ERP Core",
        "Trident Inventory Manager",
        "Trident Procurement Portal",
        "Trident Financial Ledger",
        "Trident HR Module",
        "Trident Customer Portal",
        "Trident Analytics Dash",
        "Trident Mobile App",
    ],
    "Helix Cyber": [
        "Helix XDR Platform",
        "Helix Threat Intelligence Feed",
        "Helix Deception Grid",
        "Helix Cloud Posture Manager",
        "Helix Network Detector",
        "Helix Forensics Toolkit",
        "Helix Red Team Simulator",
    ],
    "Cortex Dynamics": [
        "Cortex Autonomous Agent Framework",
        "Cortex Reinforcement Learning Suite",
        "Cortex Simulation Engine",
        "Cortex Policy Optimizer",
        "Cortex Multi-Agent Coordinator",
        "Cortex Reward Designer",
    ],
    "Fenix Automation": [
        "Fenix RPA Studio",
        "Fenix Process Recorder",
        "Fenix Bot Orchestrator",
        "Fenix Document Automator",
        "Fenix Integration Connector",
        "Fenix Monitoring Dashboard",
        "Fenix Exception Handler",
    ],
    "Crestline Cloud": [
        "Crestline Virtual Machines",
        "Crestline Managed Databases",
        "Crestline Load Balancer",
        "Crestline Private Network",
        "Crestline Blob Storage",
        "Crestline Audit Logs",
        "Crestline Spend Advisor",
    ],
    "Myriad Inference": [
        "Myriad Inference Runtime",
        "Myriad Model Quantizer",
        "Myriad Batch Predictor",
        "Myriad Edge Deployer",
        "Myriad Latency Profiler",
        "Myriad Ensemble Manager",
        "Myriad Canary Router",
    ],
    # ── Logistics ───────────────────────────────────────────────────────────────
    "Cargolux Direct": [
        "Cargolux Air Freight",
        "Cargolux Charter Service",
        "Cargolux Customs Brokerage",
        "Cargolux Cold Chain",
        "Cargolux Track & Trace Portal",
        "Cargolux Hazmat Handling",
    ],
    "Pathvex Freight": [
        "Pathvex LTL Service",
        "Pathvex FTL Service",
        "Pathvex Route Optimizer",
        "Pathvex Freight Audit",
        "Pathvex Carrier Marketplace",
        "Pathvex Shipment Visibility",
        "Pathvex Returns Management",
    ],
    "Havenport Co.": [
        "Havenport Port Handling",
        "Havenport Container Storage",
        "Havenport Vessel Scheduling",
        "Havenport Customs Filing",
        "Havenport Transshipment Service",
        "Havenport Cargo Insurance",
    ],
    "Ironline Shipping": [
        "Ironline Rail Freight",
        "Ironline Intermodal Service",
        "Ironline Bulk Cargo",
        "Ironline Wagon Leasing",
        "Ironline Cross-Border Rail",
        "Ironline Cargo Monitoring",
        "Ironline Siding Access Service",
    ],
    "Deckway Logistics": [
        "Deckway Warehouse Management",
        "Deckway Pick & Pack",
        "Deckway Cross-Docking",
        "Deckway Value-Added Services",
        "Deckway Inventory Visibility",
        "Deckway Returns Processing",
    ],
    "Surebound Courier": [
        "Surebound Same-Day Delivery",
        "Surebound Next-Day Express",
        "Surebound Signature Required",
        "Surebound Bulk Business Mail",
        "Surebound Proof of Delivery",
        "Surebound Courier API",
    ],
    "Coldrun Transport": [
        "Coldrun Refrigerated Trucking",
        "Coldrun Frozen Cargo Service",
        "Coldrun Temperature Monitoring",
        "Coldrun Pharma Cold Chain",
        "Coldrun Food-Grade Containers",
        "Coldrun Last-Mile Cold Delivery",
        "Coldrun Compliance Reporting",
    ],
    "Waymark Supply": [
        "Waymark Inventory Replenishment",
        "Waymark Demand Forecasting",
        "Waymark Supplier Portal",
        "Waymark Purchase Order Manager",
        "Waymark VMI Program",
        "Waymark Analytics Dashboard",
    ],
    "Portside Group": [
        "Portside Stevedoring Services",
        "Portside Terminal Operations",
        "Portside Ship Agency",
        "Portside Cargo Survey",
        "Portside Break-Bulk Handling",
        "Portside Marine Fueling",
    ],
    "Fasthold Inc.": [
        "Fasthold Express Parcel",
        "Fasthold Pallet Network",
        "Fasthold Locker Delivery",
        "Fasthold Scheduled Pickup",
        "Fasthold Tracking Suite",
        "Fasthold Business Account Portal",
        "Fasthold Insurance Add-On",
    ],
    "Clearspan Freight": [
        "Clearspan Over-Dimensional Freight",
        "Clearspan Heavy Haul",
        "Clearspan Permit Coordination",
        "Clearspan Pilot Car Service",
        "Clearspan Crane & Rigging",
        "Clearspan Project Cargo Management",
    ],
    "Orion Fulfillment": [
        "Orion eCommerce Fulfillment",
        "Orion Subscription Box Service",
        "Orion Kitting & Assembly",
        "Orion Returns Portal",
        "Orion Multi-Channel Sync",
        "Orion Inventory Forecaster",
        "Orion Same-Day Ship",
    ],
    "Nexhub Distribution": [
        "Nexhub Regional DC Network",
        "Nexhub Last-Mile Delivery",
        "Nexhub Sortation Services",
        "Nexhub Peak Season Flex",
        "Nexhub Retailer Compliance",
        "Nexhub Barcode & Labeling",
    ],
    "Traxion Global": [
        "Traxion Global Forwarding",
        "Traxion Ocean FCL",
        "Traxion Ocean LCL",
        "Traxion Air Express",
        "Traxion Customs Advisory",
        "Traxion Trade Compliance",
        "Traxion Shipment Dashboard",
        "Traxion Supply Chain Visibility",
    ],
    "Vertex Fleet": [
        "Vertex Fleet Management Platform",
        "Vertex Driver App",
        "Vertex Telematics Device",
        "Vertex Route Planner",
        "Vertex Maintenance Scheduler",
        "Vertex Fuel Analytics",
        "Vertex EV Fleet Transition Service",
    ],
    "Loadstone Co.": [
        "Loadstone Load Board",
        "Loadstone Carrier Vetting",
        "Loadstone Digital Bill of Lading",
        "Loadstone Freight Rate Engine",
        "Loadstone Dispatch Console",
        "Loadstone Payment Automation",
    ],
    "Bridgerun Cargo": [
        "Bridgerun Cross-Border Trucking",
        "Bridgerun Bonded Warehouse",
        "Bridgerun Duty Drawback Service",
        "Bridgerun Multimodal Booking",
        "Bridgerun Cargo Visibility App",
        "Bridgerun Freight Insurance",
    ],
    "Tidal Freight": [
        "Tidal Ocean Freight",
        "Tidal Port-to-Door",
        "Tidal Bulk Liquid Transport",
        "Tidal Reefer Service",
        "Tidal Vessel Charter",
        "Tidal Documentation Service",
        "Tidal Tracking Portal",
    ],
    "Groundlink Ops": [
        "Groundlink Ground Transport",
        "Groundlink Airport Transfers",
        "Groundlink Dedicated Truck",
        "Groundlink On-Demand Dispatch",
        "Groundlink Load Tracking",
        "Groundlink Driver Compliance Suite",
    ],
    "Duneport Logistics": [
        "Duneport Desert Freight",
        "Duneport Arid-Region Warehousing",
        "Duneport Specialized Packing",
        "Duneport Remote Area Delivery",
        "Duneport Cargo Consolidation",
        "Duneport Export Documentation",
    ],
    "Verigate Supply": [
        "Verigate Inbound Logistics",
        "Verigate Supplier Compliance",
        "Verigate Goods-in Inspection",
        "Verigate Receiving Automation",
        "Verigate Purchase Order Tracking",
        "Verigate Supply Chain Finance",
        "Verigate Vendor Scorecard",
    ],
    "Keystep Courier": [
        "Keystep Same-Day Urban Delivery",
        "Keystep Medical Courier",
        "Keystep Legal Document Service",
        "Keystep Scheduled Route",
        "Keystep Proof of Delivery App",
        "Keystep White-Glove Delivery",
    ],
    "Lanemark Freight": [
        "Lanemark LTL Consolidation",
        "Lanemark Dedicated Lane Service",
        "Lanemark Drop-Trailer Program",
        "Lanemark Freight Audit & Pay",
        "Lanemark Carrier Scorecard",
        "Lanemark Rate Management Tool",
    ],
    "Cirrus Dispatch": [
        "Cirrus Dispatch Platform",
        "Cirrus Driver Matching",
        "Cirrus Real-Time ETA",
        "Cirrus Multi-Stop Optimizer",
        "Cirrus Customer Notifications",
        "Cirrus Analytics Suite",
        "Cirrus API Integrations",
    ],
    "Peakline Transport": [
        "Peakline Mountain Freight",
        "Peakline High-Altitude Logistics",
        "Peakline Seasonal Road Planning",
        "Peakline Cold-Weather Handling",
        "Peakline Specialized Carriers",
        "Peakline Remote Site Delivery",
    ],
    "Rutherway Express": [
        "Rutherway Next-Day Parcel",
        "Rutherway Timed Delivery",
        "Rutherway B2B Express",
        "Rutherway Fragile Goods Service",
        "Rutherway International Express",
        "Rutherway Locker Network",
    ],
    "Greylock Cargo": [
        "Greylock Break-Bulk Cargo",
        "Greylock Bulk Commodities",
        "Greylock Port Agency",
        "Greylock Stowage Planning",
        "Greylock Cargo Inspection",
        "Greylock Freight Finance",
    ],
    "Strata Movers": [
        "Strata Commercial Relocation",
        "Strata IT Equipment Moving",
        "Strata Office Furniture Install",
        "Strata Laboratory Moving",
        "Strata Records Management",
        "Strata Secure Document Shredding",
        "Strata Storage Units",
    ],
    "Irongate Delivery": [
        "Irongate B2B Distribution",
        "Irongate Heavy Item Delivery",
        "Irongate Scheduled Routing",
        "Irongate White-Glove Install",
        "Irongate Reverse Logistics",
        "Irongate Tracking Dashboard",
    ],
    "Wayford Global": [
        "Wayford Global Trade Management",
        "Wayford Export Compliance",
        "Wayford Tariff Classification",
        "Wayford Denied Party Screening",
        "Wayford Import Duty Optimizer",
        "Wayford Free Trade Zone Services",
        "Wayford Regulatory Filing",
        "Wayford Supply Chain Consulting",
    ],
    # ── Materials ───────────────────────────────────────────────────────────────
    "Corevast Materials": [
        "Corevast Structural Panel",
        "Corevast Load-Bearing Foam",
        "Corevast Sandwich Composite",
        "Corevast Fire-Rated Board",
        "Corevast Acoustic Barrier",
        "Corevast Lightweight Core Sheet",
    ],
    "Ironveil Industries": [
        "Ironveil Sheet Steel",
        "Ironveil Galvanized Coil",
        "Ironveil Perforated Plate",
        "Ironveil Expanded Metal",
        "Ironveil Welded Wire Mesh",
        "Ironveil Surface Treatment Services",
        "Ironveil Custom Fabrication",
    ],
    "Altrex Composites": [
        "Altrex Carbon Fiber Prepreg",
        "Altrex Fiberglass Laminate",
        "Altrex Aramid Weave",
        "Altrex Hybrid Panel",
        "Altrex Resin Transfer Mold Kit",
        "Altrex Composite Tube",
        "Altrex NDT Testing Service",
    ],
    "Densium Corp.": [
        "Densium High-Density Foam",
        "Densium Vibration Isolator",
        "Densium Impact Liner",
        "Densium Acoustic Tile",
        "Densium Cushion Roll",
        "Densium Custom Die-Cut Parts",
    ],
    "Ferrovance Ltd.": [
        "Ferrovance Precision Steel Bar",
        "Ferrovance Alloy Rod",
        "Ferrovance Cold-Drawn Wire",
        "Ferrovance Forged Blanks",
        "Ferrovance Centerless Grinding Service",
        "Ferrovance Material Certification",
    ],
    "Oskar Alloys": [
        "Oskar Nickel Superalloy",
        "Oskar Cobalt Alloy Billet",
        "Oskar Titanium Sponge",
        "Oskar Refractory Ingot",
        "Oskar Master Alloy Blend",
        "Oskar Alloy Analysis Service",
        "Oskar Custom Melt Program",
    ],
    "Stonebridge Chem.": [
        "Stonebridge Industrial Solvent",
        "Stonebridge Specialty Resin",
        "Stonebridge Surface Cleaner",
        "Stonebridge Polymer Additive",
        "Stonebridge Catalyst Blend",
        "Stonebridge Process Chemical",
        "Stonebridge MSDS Compliance Kit",
    ],
    "Caldera Minerals": [
        "Caldera Silica Sand",
        "Caldera Feldspar Powder",
        "Caldera Kaolin Clay",
        "Caldera Talc Mineral",
        "Caldera Calcium Carbonate",
        "Caldera Barite Filler",
        "Caldera Custom Mineral Blends",
    ],
    "Pyrex Advanced": [
        "Pyrex Borosilicate Sheet",
        "Pyrex Lab Glass Tubing",
        "Pyrex High-Temp Glass Rod",
        "Pyrex Custom Blown Components",
        "Pyrex Optical Glass Blank",
        "Pyrex Tempered Safety Glass",
    ],
    "Silven Coatings": [
        "Silven Anti-Corrosion Primer",
        "Silven Thermal Barrier Coat",
        "Silven UV-Cure Topcoat",
        "Silven Non-Stick Release Coat",
        "Silven Ceramic Spray",
        "Silven Electrostatic Powder Coat",
        "Silven Custom Color Matching",
    ],
    "Auric Metals": [
        "Auric Gold Sheet",
        "Auric Silver Wire",
        "Auric Platinum Sponge",
        "Auric Palladium Granule",
        "Auric Precious Metal Refining",
        "Auric Assay Services",
        "Auric Secure Storage",
    ],
    "Carbide Works": [
        "Carbide Works Tungsten Rod",
        "Carbide Works Cemented Carbide Insert",
        "Carbide Works End Mill Blank",
        "Carbide Works Die & Punch",
        "Carbide Works Custom Carbide Parts",
        "Carbide Works Regrind Service",
    ],
    "Molten Dynamics": [
        "Molten Dynamics Casting Alloy",
        "Molten Dynamics Die Cast Blank",
        "Molten Dynamics Sand-Cast Component",
        "Molten Dynamics Investment Cast Part",
        "Molten Dynamics Heat Treatment",
        "Molten Dynamics Alloy Consulting",
    ],
    "Vantage Fiber": [
        "Vantage Carbon Fiber Tow",
        "Vantage Basalt Fiber Roving",
        "Vantage Glass Fiber Mat",
        "Vantage Woven Fabric Roll",
        "Vantage Chopped Strand",
        "Vantage Filament Winding Service",
        "Vantage Fiber Sizing Chemistry",
    ],
    "Steelbrook Group": [
        "Steelbrook Hot-Rolled Coil",
        "Steelbrook Cold-Rolled Sheet",
        "Steelbrook Structural Beam",
        "Steelbrook Hollow Section",
        "Steelbrook Steel Plate",
        "Steelbrook Slitting & Blanking",
        "Steelbrook Inventory Consignment",
    ],
    "Graphene One": [
        "Graphene One Monolayer Film",
        "Graphene One Oxide Powder",
        "Graphene One Ink Formulation",
        "Graphene One Composite Additive",
        "Graphene One Thermal Interface Sheet",
        "Graphene One R&D Consulting",
    ],
    "Halcyon Polymers": [
        "Halcyon Engineering Plastic Pellet",
        "Halcyon High-Performance Film",
        "Halcyon Elastomer Compound",
        "Halcyon Foam Extrusion",
        "Halcyon Polymer Alloy",
        "Halcyon Recycled Resin Blend",
        "Halcyon Custom Compounding",
    ],
    "Terrain Materials": [
        "Terrain Geotextile Fabric",
        "Terrain Drainage Geocomposite",
        "Terrain Erosion Control Mat",
        "Terrain Road Base Aggregate",
        "Terrain Gabion Stone",
        "Terrain Retaining Wall Block",
    ],
    "Borax Innovations": [
        "Borax Fire Retardant Compound",
        "Borax Wood Preservative",
        "Borax Flux Agent",
        "Borax Insulation Additive",
        "Borax Industrial Cleaner",
        "Borax Agriculture-Grade Boron",
    ],
    "Quartzite Labs": [
        "Quartzite High-Purity Quartz",
        "Quartzite Silica Wafer Substrate",
        "Quartzite Fused Silica Rod",
        "Quartzite Crystal Oscillator Blank",
        "Quartzite Surface Polishing Service",
        "Quartzite Chemical Analysis",
    ],
    "Forgepoint Co.": [
        "Forgepoint Open-Die Forgings",
        "Forgepoint Ring Rolled Forgings",
        "Forgepoint Closed-Die Stampings",
        "Forgepoint Seamless Rolled Ring",
        "Forgepoint Heat Treat & Proof",
        "Forgepoint Material Traceability Service",
    ],
    "Magnox Materials": [
        "Magnox Magnesium Alloy Billet",
        "Magnox Die Cast Ingot",
        "Magnox Rolled Sheet",
        "Magnox Extrusion Profile",
        "Magnox Sacrificial Anode",
        "Magnox Surface Passivation Service",
    ],
    "Cresteel Inc.": [
        "Cresteel Stainless Bar",
        "Cresteel Duplex Sheet",
        "Cresteel Super Duplex Pipe",
        "Cresteel Passivation Treatment",
        "Cresteel Custom Stainless Fabrication",
        "Cresteel Quality Certification",
    ],
    "Lithos Advanced": [
        "Lithos Lithium Carbonate",
        "Lithos Battery-Grade Hydroxide",
        "Lithos Cathode Precursor",
        "Lithos Solid Electrolyte Powder",
        "Lithos Li-Ion Cell Coating",
        "Lithos Recycling & Recovery Service",
    ],
    "Oxara Coatings": [
        "Oxara Alumina Plasma Coat",
        "Oxara Zirconia Thermal Spray",
        "Oxara Hard Chrome Replacement",
        "Oxara HVOF Carbide Coat",
        "Oxara DLC Thin Film",
        "Oxara Coating Thickness Testing",
        "Oxara Repair & Recoat Service",
    ],
    "Pelite Industries": [
        "Pelite Expanded Perlite",
        "Pelite Perlite Filter Aid",
        "Pelite Horticultural Aggregate",
        "Pelite Cryogenic Insulation Fill",
        "Pelite Lightweight Concrete Mix",
        "Pelite Custom-Grade Perlite",
    ],
    "Endura Alloys": [
        "Endura Wear-Resistant Plate",
        "Endura Chromium Carbide Overlay",
        "Endura Bimetallic Sheet",
        "Endura Hard-Facing Wire",
        "Endura Abrasion-Resistant Casting",
        "Endura Custom Liner Program",
    ],
    "Vitrex Corp.": [
        "Vitrex Ceramic Tile",
        "Vitrex Porcelain Slab",
        "Vitrex Technical Ceramic Component",
        "Vitrex Refractory Brick",
        "Vitrex Glass-Ceramic Substrate",
        "Vitrex Custom Glazing Service",
    ],
    "Titan Substrate": [
        "Titan PCB Laminate",
        "Titan Ceramic Substrate",
        "Titan Metal-Core Board",
        "Titan Flexible Dielectric Film",
        "Titan Thermal Management Pad",
        "Titan Custom Panel Fabrication",
    ],
    "Nullstone Materials": [
        "Nullstone Aerogel Blanket",
        "Nullstone Aerogel Granule",
        "Nullstone Thermal Insulation Panel",
        "Nullstone Cryogenic Pipe Wrap",
        "Nullstone Fire Barrier Blanket",
        "Nullstone R&D Aerogel Samples",
    ],
    "Verdant Biopolymers": [
        "Verdant PLA Resin",
        "Verdant PHA Pellet",
        "Verdant Compostable Film",
        "Verdant Bio-Based Foam",
        "Verdant Starch Blend Compound",
        "Verdant Biodegradable Adhesive",
        "Verdant Composting Certification",
    ],
    "Ashford Mineral Co.": [
        "Ashford Crushed Limestone",
        "Ashford Dolomite Aggregate",
        "Ashford Ground Calcium Carbonate",
        "Ashford Ag-Lime Spread Service",
        "Ashford Marble Chips",
        "Ashford Custom Stone Blend",
    ],
    "Orespan Ltd.": [
        "Orespan Iron Ore Concentrate",
        "Orespan Copper Concentrate",
        "Orespan Zinc Sinter",
        "Orespan Lead Bullion",
        "Orespan Precious Metal Byproduct",
        "Orespan Assay & Analysis Service",
        "Orespan Off-Take Agreements",
    ],
    "Crestline Ceramics": [
        "Crestline Alumina Crucible",
        "Crestline Silicon Carbide Tube",
        "Crestline Cordierite Kiln Furniture",
        "Crestline Wear-Resistant Lining",
        "Crestline Custom Ceramic Component",
        "Crestline Sintering Service",
    ],
    "Ferralign Inc.": [
        "Ferralign Alignment Bar",
        "Ferralign Ground Flat Stock",
        "Ferralign Precision Shim",
        "Ferralign Jig & Fixture Plate",
        "Ferralign Straightness Testing",
        "Ferralign Custom Flat Bar",
    ],
    "Novacite Corp.": [
        "Novacite Muscovite Mica",
        "Novacite Phlogopite Sheet",
        "Novacite Electrical Insulation Tape",
        "Novacite Mica Powder",
        "Novacite Thermal Mica Plate",
        "Novacite Custom Mica Parts",
    ],
    "Thermex Fiber": [
        "Thermex Ceramic Fiber Blanket",
        "Thermex Refractory Board",
        "Thermex High-Temp Module",
        "Thermex Insulating Castable",
        "Thermex Fiber Paper",
        "Thermex Furnace Lining Service",
        "Thermex Anchor & Hardware Kit",
    ],
    "Rigel Composites": [
        "Rigel Pultruded Profile",
        "Rigel Filament Wound Tube",
        "Rigel Sandwich Panel",
        "Rigel SMC Sheet",
        "Rigel BMC Molding Compound",
        "Rigel Custom Composite Parts",
        "Rigel Structural Design Service",
    ],
    "Duratek Advanced": [
        "Duratek Ultra-Hard Coating",
        "Duratek Wear Tile",
        "Duratek Abrasion-Resistant Pipe",
        "Duratek Ceramic-Lined Elbow",
        "Duratek Impact Bar",
        "Duratek Retrofit Lining Service",
    ],
    "Heliox Materials": [
        "Heliox Optical Film",
        "Heliox Photovoltaic Encapsulant",
        "Heliox UV-Blocking Sheet",
        "Heliox Anti-Reflective Coat",
        "Heliox Light-Management Film",
        "Heliox Solar Laminate Kit",
    ],
    # ── Entertainment ───────────────────────────────────────────────────────────
    "Luminary Studios": [
        "Luminary Originals (streaming series)",
        "Luminary Documentary Label",
        "Luminary Post-Production Services",
        "Luminary Music Scoring Suite",
        "Luminary VFX Pipeline",
        "Luminary Licensing & Distribution",
        "Luminary Creator Fund",
    ],
    "Echoplex Media": [
        "Echoplex Podcast Network",
        "Echoplex Audio Dramas",
        "Echoplex Live Event Coverage",
        "Echoplex Brand Audio Identity",
        "Echoplex Spatial Audio Studio",
        "Echoplex Sync Licensing",
    ],
    "Vortex Entertainment": [
        "Vortex Live Events",
        "Vortex Ticketing Platform",
        "Vortex Artist Management",
        "Vortex Venue Partnership Program",
        "Vortex Merch & Fulfillment",
        "Vortex Fan Engagement App",
        "Vortex Sponsorship Activation",
    ],
    "Prism Pictures": [
        "Prism Feature Films",
        "Prism Co-Production Fund",
        "Prism Film Festival Circuit Service",
        "Prism Digital Distribution",
        "Prism International Sales",
        "Prism Talent Development Program",
    ],
    "Wildframe Films": [
        "Wildframe Nature Documentaries",
        "Wildframe Wildlife Stock Footage",
        "Wildframe Aerial Cinematography",
        "Wildframe Educational Series",
        "Wildframe Conservation Partnerships",
        "Wildframe Archive Licensing",
    ],
    "Resonant Audio": [
        "Resonant Recording Studio",
        "Resonant Mastering Suite",
        "Resonant Foley & SFX Library",
        "Resonant Live Sound Engineering",
        "Resonant Podcast Production",
        "Resonant Music Publishing",
        "Resonant Online Mixing Service",
    ],
    "Nightfall Games": [
        "Nightfall RPG Title",
        "Nightfall Horror Series",
        "Nightfall Open-World Engine",
        "Nightfall DLC Season Pass",
        "Nightfall Modding Toolkit",
        "Nightfall Esports League",
        "Nightfall Mobile Companion App",
    ],
    "Starfield Studios": [
        "Starfield Sci-Fi Drama Series",
        "Starfield VR Experience",
        "Starfield Concept Art Book",
        "Starfield Soundtrack Album",
        "Starfield Collectible Figures",
        "Starfield Fan Convention",
    ],
    "Canopy Creative": [
        "Canopy Animated Series",
        "Canopy Children's Content",
        "Canopy Character Licensing",
        "Canopy Educational Games",
        "Canopy Publishing Line",
        "Canopy Live Stage Show",
        "Canopy Theme Park Partnerships",
    ],
    "Ironwood Pictures": [
        "Ironwood Prestige Drama Films",
        "Ironwood Director's Guild Program",
        "Ironwood Indie Development Fund",
        "Ironwood Film Academy",
        "Ironwood Theatrical Distribution",
        "Ironwood Awards Campaign Service",
    ],
    "Wavefront Media": [
        "Wavefront Streaming Platform",
        "Wavefront Creator Studio",
        "Wavefront Ad Network",
        "Wavefront Content Analytics",
        "Wavefront Live Sports Rights",
        "Wavefront Subscriber Insights Tool",
    ],
    "Celestial Films": [
        "Celestial Epic Fantasy Series",
        "Celestial Location Scouting Service",
        "Celestial Costume Design Studio",
        "Celestial International Co-Pro",
        "Celestial Film Score Label",
        "Celestial World-Building Bible",
    ],
    "Dawnbreak Games": [
        "Dawnbreak Strategy Title",
        "Dawnbreak Card Game",
        "Dawnbreak Early Access Program",
        "Dawnbreak Game Jam Platform",
        "Dawnbreak Indie Publishing Label",
        "Dawnbreak Speedrun Events",
    ],
    "Meridian Entertainment": [
        "Meridian Talent Agency",
        "Meridian Brand Partnerships",
        "Meridian Streaming Deals",
        "Meridian Tour Management",
        "Meridian Digital Content Studio",
        "Meridian PR & Media Services",
        "Meridian Royalty Administration",
    ],
    "Hollow Oak Studios": [
        "Hollow Oak Narrative Adventure Games",
        "Hollow Oak Studio Artbook",
        "Hollow Oak Composer Collective",
        "Hollow Oak Kickstarter Services",
        "Hollow Oak Community Discord",
        "Hollow Oak Physical Collector's Edition",
    ],
    "Redline Records": [
        "Redline Artist Roster",
        "Redline A&R Consulting",
        "Redline Distribution Network",
        "Redline Sync Licensing",
        "Redline Music Video Production",
        "Redline Vinyl & Merch Store",
        "Redline Publishing Division",
    ],
    "Apex Animations": [
        "Apex 3D Animation Studio",
        "Apex Motion Capture Service",
        "Apex Character Rigging",
        "Apex Previz & Storyboarding",
        "Apex VFX Compositing",
        "Apex Animated Advertising",
        "Apex Real-Time Rendering Pipeline",
    ],
    "Solstice Media": [
        "Solstice Digital Magazine",
        "Solstice Newsletter Platform",
        "Solstice Brand Content Studio",
        "Solstice Influencer Network",
        "Solstice Video Production",
        "Solstice Media Buying",
    ],
    "Fable Interactive": [
        "Fable Story-Driven RPG",
        "Fable World Map Generator",
        "Fable Lore Companion App",
        "Fable Tabletop Spin-Off",
        "Fable Interactive Novel",
        "Fable Fan Art Contest Platform",
        "Fable Merchandise Line",
    ],
    "Cinemark Creative": [
        "Cinemark Commercial Production",
        "Cinemark Corporate Video",
        "Cinemark Event Filming",
        "Cinemark Color Grading Suite",
        "Cinemark Short Film Program",
        "Cinemark Social Media Content",
    ],
    "Drift Studios": [
        "Drift Racing Game",
        "Drift eSports Tournament",
        "Drift Car Customization DLC",
        "Drift Arcade Cabinet",
        "Drift Mobile Edition",
        "Drift Merchandise",
        "Drift Community Mods Platform",
    ],
    "Ember Entertainment": [
        "Ember Fantasy Novel Series",
        "Ember Audiobook Label",
        "Ember Tabletop RPG",
        "Ember Graphic Novel Line",
        "Ember Author Residency Program",
        "Ember Fan Convention",
    ],
    "Goldveil Films": [
        "Goldveil Thriller Film Series",
        "Goldveil Script Development Service",
        "Goldveil Producer Attachments",
        "Goldveil Film Finance Advisory",
        "Goldveil Talent Representation",
        "Goldveil International Distribution",
    ],
    "Arclight Productions": [
        "Arclight Live Concert Films",
        "Arclight Music Documentary",
        "Arclight Stage Production",
        "Arclight Behind-the-Scenes Series",
        "Arclight Artist Branding",
        "Arclight Streaming Specials",
    ],
    "Reverie Games": [
        "Reverie Dream Exploration Title",
        "Reverie Puzzle Adventure",
        "Reverie Soundtrack Edition",
        "Reverie Level Design Tools",
        "Reverie Community Mod Kit",
        "Reverie Collector's Hardcover Art Book",
    ],
    "Tempest Audio": [
        "Tempest Studio Monitors",
        "Tempest DAW Plugin Suite",
        "Tempest Sample Library",
        "Tempest Live Mixing Console",
        "Tempest Broadcast Encoder",
        "Tempest Immersive Audio Renderer",
        "Tempest Online Collaboration Suite",
    ],
    "Blackwater Media": [
        "Blackwater True-Crime Podcast",
        "Blackwater Investigative Documentary",
        "Blackwater Digital Newsroom",
        "Blackwater Freelance Contributor Network",
        "Blackwater Licensing & Syndication",
        "Blackwater Documentary Licensing",
    ],
    "Verdant Pictures": [
        "Verdant Eco-Thriller Series",
        "Verdant Climate Documentary",
        "Verdant Green Production Certification",
        "Verdant Carbon-Neutral Film Fund",
        "Verdant Nature Stock Library",
        "Verdant Sustainability Report Service",
    ],
    "Foxrun Studios": [
        "Foxrun Family Film Series",
        "Foxrun Animation Division",
        "Foxrun Theme Song Library",
        "Foxrun Children's App",
        "Foxrun Plush Toy Licensing",
        "Foxrun Educational DVD Line",
    ],
    "Neon Horizon Games": [
        "Neon Horizon Cyberpunk RPG",
        "Neon Horizon Battle Royale",
        "Neon Horizon Season Pass",
        "Neon Horizon Esports League",
        "Neon Horizon Cosmetic Store",
        "Neon Horizon Mobile Port",
        "Neon Horizon Game Soundtrack",
        "Neon Horizon Community Tournament Kit",
    ],
    # ── Finance ──────────────────────────────────────────────────────────────────
    "Aurum Capital": [
        "Aurum Growth Fund",
        "Aurum Precious Metals ETF",
        "Aurum Alternative Assets Portfolio",
        "Aurum Private Credit",
        "Aurum Wealth Management",
        "Aurum Family Office Services",
        "Aurum ESG Strategy",
    ],
    "Vantage Equity": [
        "Vantage Small-Cap Fund",
        "Vantage Mid-Cap Growth",
        "Vantage Dividend Income Portfolio",
        "Vantage Sector Rotation Strategy",
        "Vantage Separately Managed Accounts",
        "Vantage Institutional Research",
    ],
    "Crestmark Advisors": [
        "Crestmark Retirement Planning",
        "Crestmark Tax-Efficient Portfolios",
        "Crestmark Estate Planning",
        "Crestmark 401(k) Advisory",
        "Crestmark Insurance Review",
        "Crestmark Financial Plan Builder",
        "Crestmark Client Portal",
    ],
    "Ironfield Partners": [
        "Ironfield Infrastructure Fund",
        "Ironfield Private Equity",
        "Ironfield Real Assets Strategy",
        "Ironfield Co-Investment Program",
        "Ironfield LP Advisory",
        "Ironfield Deal Origination",
    ],
    "Solent Capital": [
        "Solent Hedge Fund",
        "Solent Long/Short Equity",
        "Solent Macro Strategy",
        "Solent Risk Overlay Service",
        "Solent Prime Brokerage Advisory",
        "Solent Investor Relations Portal",
    ],
    "Verdian Wealth": [
        "Verdian Sustainable Portfolio",
        "Verdian Impact Bonds",
        "Verdian Green REIT",
        "Verdian ESG Screening Tool",
        "Verdian Carbon Credit Strategy",
        "Verdian Responsible Endowment Advisory",
        "Verdian Annual Impact Report",
    ],
    "Nexbridge Finance": [
        "Nexbridge Commercial Loans",
        "Nexbridge Bridge Financing",
        "Nexbridge Equipment Leasing",
        "Nexbridge Invoice Factoring",
        "Nexbridge Revenue-Based Financing",
        "Nexbridge Credit Line",
    ],
    "Halcyon Funds": [
        "Halcyon Balanced Fund",
        "Halcyon Bond Ladder",
        "Halcyon Capital Preservation Strategy",
        "Halcyon Charitable Giving Portal",
        "Halcyon Endowment Management",
        "Halcyon Trust Services",
    ],
    "Stratum Capital": [
        "Stratum Venture Fund",
        "Stratum Growth Equity",
        "Stratum Seed Program",
        "Stratum Founder Advisory",
        "Stratum Portfolio Monitoring Platform",
        "Stratum LP Reporting Suite",
        "Stratum Deal Flow Network",
    ],
    "Clearview Advisors": [
        "Clearview Financial Planning",
        "Clearview Investment Review",
        "Clearview College Savings Plan",
        "Clearview Business Succession Advisory",
        "Clearview Insurance Analysis",
        "Clearview Net Worth Tracker",
    ],
    "Pinnacle Asset Mgmt.": [
        "Pinnacle Core Equity",
        "Pinnacle Fixed Income",
        "Pinnacle Multi-Asset Strategy",
        "Pinnacle Liability-Driven Investing",
        "Pinnacle Custom Index",
        "Pinnacle Institutional Consulting",
        "Pinnacle Reporting Platform",
    ],
    "Greystone Equity": [
        "Greystone Value Fund",
        "Greystone Activist Strategy",
        "Greystone Special Situations",
        "Greystone Proxy Advisory",
        "Greystone Shareholder Engagement",
        "Greystone Research Desk",
    ],
    "Tidewater Capital": [
        "Tidewater Maritime Finance",
        "Tidewater Ship Mortgage",
        "Tidewater Vessel Leasing",
        "Tidewater Port Infrastructure Fund",
        "Tidewater Trade Finance",
        "Tidewater Insurance Captive",
    ],
    "Fortem Finance": [
        "Fortem Business Loans",
        "Fortem SBA Lending",
        "Fortem Commercial Mortgage",
        "Fortem Trade Finance",
        "Fortem Treasury Management",
        "Fortem Online Banking Portal",
    ],
    "Axle Investments": [
        "Axle Mobility & Transport Fund",
        "Axle Fleet Finance",
        "Axle EV Infrastructure Fund",
        "Axle Logistics REIT",
        "Axle Infrastructure Debt",
        "Axle Sector Research",
    ],
    "Cormorant Wealth": [
        "Cormorant Coastal Real Estate Fund",
        "Cormorant Blue Economy Portfolio",
        "Cormorant Marine Renewable Energy",
        "Cormorant Aquaculture Investment",
        "Cormorant Impact Wealth Advisory",
        "Cormorant Philanthropy Services",
    ],
    "Bridgewater Advisory": [
        "Bridgewater M&A Advisory",
        "Bridgewater Capital Raise",
        "Bridgewater Valuation Services",
        "Bridgewater Due Diligence",
        "Bridgewater Exit Planning",
        "Bridgewater Fairness Opinion",
        "Bridgewater Restructuring Advisory",
    ],
    "Thorngate Capital": [
        "Thorngate Long-Term Equity Fund",
        "Thorngate Concentrated Portfolio",
        "Thorngate Compounding Strategy",
        "Thorngate Business Owner Advisory",
        "Thorngate Family Capital Planning",
        "Thorngate Tax Deferral Strategy",
    ],
    "Luminos Finance": [
        "Luminos Consumer Lending",
        "Luminos BNPL Platform",
        "Luminos Credit Score Builder",
        "Luminos Personal Finance App",
        "Luminos Savings Account",
        "Luminos Rewards Credit Card",
    ],
    "Harrow Equity": [
        "Harrow Agricultural Land Fund",
        "Harrow Farmland REIT",
        "Harrow Rural Infrastructure Debt",
        "Harrow Agri-Tech Venture Fund",
        "Harrow Carbon Sequestration Credits",
        "Harrow Land Advisory",
    ],
    "Redstone Partners": [
        "Redstone Growth Equity",
        "Redstone Buyout Fund",
        "Redstone Industrial Sector Strategy",
        "Redstone Portfolio Operations",
        "Redstone Management Incentive Plans",
        "Redstone LP Relations Platform",
    ],
    "Velox Capital": [
        "Velox Algorithmic Trading Desk",
        "Velox Quantitative Fund",
        "Velox Market-Making Service",
        "Velox Risk Management Suite",
        "Velox Execution Analytics",
        "Velox Prime Services",
        "Velox Alternative Data Feed",
    ],
    "Cavendish Funds": [
        "Cavendish Global Macro Fund",
        "Cavendish Multi-Strategy",
        "Cavendish Event-Driven Fund",
        "Cavendish Managed Futures",
        "Cavendish Currency Overlay",
        "Cavendish Risk Parity",
    ],
    "Irongate Advisors": [
        "Irongate Pension Consulting",
        "Irongate Defined Benefit Strategy",
        "Irongate Asset Liability Matching",
        "Irongate Governance Advisory",
        "Irongate Investment Policy Review",
        "Irongate Manager Selection",
    ],
    "Sterling Meridian": [
        "Sterling Meridian Private Banking",
        "Sterling Meridian Investment Portfolio",
        "Sterling Meridian Currency Exchange",
        "Sterling Meridian International Trust",
        "Sterling Meridian Structured Products",
        "Sterling Meridian Concierge Service",
        "Sterling Meridian Digital Banking App",
    ],
    "Bastion Wealth": [
        "Bastion Capital Preservation Fund",
        "Bastion Inflation-Protected Portfolio",
        "Bastion Real Asset Allocation",
        "Bastion Generational Wealth Transfer",
        "Bastion Trust & Estates",
        "Bastion Foundation Services",
    ],
    "Primus Capital": [
        "Primus First-Loss Tranche",
        "Primus Mezzanine Debt",
        "Primus Unitranche Facility",
        "Primus Structured Credit",
        "Primus Private Placement",
        "Primus Borrower Advisory",
    ],
    "Quorum Finance": [
        "Quorum Corporate Finance",
        "Quorum Debt Capital Markets",
        "Quorum Equity Capital Markets",
        "Quorum Syndicated Loans",
        "Quorum Rating Advisory",
        "Quorum Investor Relations Support",
        "Quorum ESG Financing",
    ],
    "Aldgate Partners": [
        "Aldgate Real Estate Private Equity",
        "Aldgate Urban Development Fund",
        "Aldgate Opportunistic Debt",
        "Aldgate Asset Management Services",
        "Aldgate JV Structuring",
        "Aldgate Property Valuation",
    ],
    "Oakthorn Investments": [
        "Oakthorn Endowment Strategy",
        "Oakthorn Alternative Investment Portfolio",
        "Oakthorn Timber & Natural Resources",
        "Oakthorn Private Credit",
        "Oakthorn Co-Investment Access",
        "Oakthorn Charitable Foundation Advisory",
        "Oakthorn Long-Horizon Equity",
    ],
    # ── Manufacturing ────────────────────────────────────────────────────────────
    "Ironclad Fabrication": [
        "Ironclad Steel Structures",
        "Ironclad Custom Metal Frames",
        "Ironclad CNC Cutting Service",
        "Ironclad Welding & Assembly",
        "Ironclad Surface Treatment",
        "Ironclad Prototype Builds",
        "Ironclad Field Installation",
    ],
    "Vortex Industrial": [
        "Vortex Industrial Fans",
        "Vortex Dust Collection Systems",
        "Vortex Pneumatic Conveying",
        "Vortex Air Filtration Units",
        "Vortex HVAC Modules",
        "Vortex Blower Service & Repair",
    ],
    "Steelmark Manufacturing": [
        "Steelmark Structural Steel",
        "Steelmark Ornamental Railing",
        "Steelmark Custom Stampings",
        "Steelmark Laser Cutting",
        "Steelmark Roll Forming",
        "Steelmark Powder Coating",
        "Steelmark Certified Welding",
    ],
    "Crestforge Works": [
        "Crestforge Drop Forgings",
        "Crestforge Open-Die Components",
        "Crestforge Heat Treatment",
        "Crestforge Rough Machining",
        "Crestforge Material Testing",
        "Crestforge Custom Alloy Forgings",
    ],
    "Duralux Corp.": [
        "Duralux Anodized Aluminum Extrusions",
        "Duralux Architectural Profiles",
        "Duralux Custom Extrusion Dies",
        "Duralux Surface Finishing",
        "Duralux Cut-to-Length Service",
        "Duralux Precision Machining",
        "Duralux Assembly & Kitting",
    ],
    "Apex Machining": [
        "Apex CNC Milling",
        "Apex CNC Turning",
        "Apex EDM Service",
        "Apex CMM Inspection",
        "Apex Prototype Machining",
        "Apex Production Run Parts",
        "Apex Design for Manufacturing Review",
    ],
    "Solaris Industrial": [
        "Solaris Solar Panel Frames",
        "Solaris Mounting Hardware",
        "Solaris Tracker Components",
        "Solaris Enclosure Fabrication",
        "Solaris Cable Management Systems",
        "Solaris Field Assembly Service",
    ],
    "Bridgeton Manufacturing": [
        "Bridgeton Precision Castings",
        "Bridgeton Machined Assemblies",
        "Bridgeton Sub-Assembly Build",
        "Bridgeton Jig & Fixture Build",
        "Bridgeton Quality Inspection Service",
        "Bridgeton Packaging & Kitting",
        "Bridgeton Production Engineering",
    ],
    "Tekton Works": [
        "Tekton Sheet Metal Fabrication",
        "Tekton Welded Assemblies",
        "Tekton Custom Enclosures",
        "Tekton Press Brake Forming",
        "Tekton Spot Welding",
        "Tekton Industrial Painting",
        "Tekton Design Assist Service",
    ],
    "Forgemaster Inc.": [
        "Forgemaster Closed-Die Forgings",
        "Forgemaster Rolled Ring Forgings",
        "Forgemaster Alloy Steel Parts",
        "Forgemaster Stainless Forgings",
        "Forgemaster Titanium Forgings",
        "Forgemaster Non-Destructive Testing",
        "Forgemaster Machining & Finishing",
    ],
    "Halcyon Precision": [
        "Halcyon Micro-Machined Parts",
        "Halcyon Swiss Screw Machining",
        "Halcyon Precision Grinding",
        "Halcyon Tight-Tolerance Turned Parts",
        "Halcyon Gear Cutting",
        "Halcyon CMM Measurement Reports",
    ],
    "Stratum Industrial": [
        "Stratum Process Equipment",
        "Stratum Pressure Vessels",
        "Stratum Heat Exchangers",
        "Stratum Skid Packages",
        "Stratum Pipe Fabrication",
        "Stratum Field Erection Service",
        "Stratum ASME Certification",
    ],
    "Ironvale Manufacturing": [
        "Ironvale Structural Components",
        "Ironvale Robotic Welding",
        "Ironvale Automated Assembly Line",
        "Ironvale Press Shop Products",
        "Ironvale Surface Prep & Coat",
        "Ironvale Lean Manufacturing Consulting",
    ],
    "Nexforge Corp.": [
        "Nexforge Aluminum Forgings",
        "Nexforge Magnesium Forgings",
        "Nexforge Copper Forgings",
        "Nexforge Precision Trim Die",
        "Nexforge Rapid Tooling",
        "Nexforge Material Traceability Reporting",
    ],
    "Pinnacle Tooling": [
        "Pinnacle Injection Mold",
        "Pinnacle Die Cast Die",
        "Pinnacle Progressive Die",
        "Pinnacle Mold Repair Service",
        "Pinnacle EDM Electrode",
        "Pinnacle Tool Try-Out Service",
        "Pinnacle Mold Flow Analysis",
    ],
    "Verdant Industrial": [
        "Verdant Recycled Material Components",
        "Verdant Green Machining",
        "Verdant Bio-Lubricant Service",
        "Verdant Energy-Efficient Assembly",
        "Verdant Scrap Recovery Program",
        "Verdant Environmental Compliance Reporting",
    ],
    "Clearfield Works": [
        "Clearfield Custom Fabrication",
        "Clearfield Modular Structures",
        "Clearfield Architectural Metalwork",
        "Clearfield Repair & Refab",
        "Clearfield Tank Fabrication",
        "Clearfield On-Site Welding",
    ],
    "Ashton Fabrication": [
        "Ashton Stainless Fabrication",
        "Ashton Food-Grade Equipment",
        "Ashton Sanitary Welding",
        "Ashton Hygienic Process Vessels",
        "Ashton Custom Stainless Enclosures",
        "Ashton Passivation Service",
    ],
    "Tidewell Manufacturing": [
        "Tidewell Marine Components",
        "Tidewell Offshore Equipment Parts",
        "Tidewell Corrosion-Resistant Fabrication",
        "Tidewell Subsea Assembly",
        "Tidewell Protective Coating",
        "Tidewell NDT Inspection",
        "Tidewell Pressure Test",
    ],
    "Greymark Corp.": [
        "Greymark Specialty Fasteners",
        "Greymark Hex Bolts & Studs",
        "Greymark Custom Threaded Parts",
        "Greymark Cold-Headed Components",
        "Greymark Nut & Washer Sets",
        "Greymark Locking Fastener Systems",
    ],
    "Redline Industrial": [
        "Redline High-Temp Components",
        "Redline Exhaust System Parts",
        "Redline Furnace Hardware",
        "Redline Refractory Anchors",
        "Redline Heat Shield Fabrication",
        "Redline Thermal Barrier Coated Parts",
    ],
    "Vanguard Machining": [
        "Vanguard Defense Components",
        "Vanguard Aerospace Machined Parts",
        "Vanguard AS9100 Certified Machining",
        "Vanguard ITAR-Compliant Parts",
        "Vanguard 5-Axis Milling",
        "Vanguard First Article Inspection",
        "Vanguard Long-Run Production",
    ],
    "Stonehurst Works": [
        "Stonehurst Architectural Stonework",
        "Stonehurst Cast Stone",
        "Stonehurst Precast Concrete Elements",
        "Stonehurst Stone Restoration",
        "Stonehurst Custom Masonry",
        "Stonehurst On-Site Installation",
    ],
    "Fenwick Manufacturing": [
        "Fenwick Conveyor Components",
        "Fenwick Roller Assemblies",
        "Fenwick Drive Pulley",
        "Fenwick Belt & Chain Drives",
        "Fenwick Idler Frames",
        "Fenwick Conveyor Maintenance Service",
        "Fenwick Custom Conveyor Design",
    ],
    "Ironshore Corp.": [
        "Ironshore Hardened Steel Parts",
        "Ironshore Case-Hardening Service",
        "Ironshore Wear Plate Machining",
        "Ironshore Induction Hardening",
        "Ironshore Shot Blast & Peen",
        "Ironshore Metallurgical Lab Services",
    ],
    "Crestwell Precision": [
        "Crestwell Optical Encoder Components",
        "Crestwell Medical Device Machining",
        "Crestwell ISO 13485 Certified Parts",
        "Crestwell Ultra-Fine Grinding",
        "Crestwell Clean-Room Assembly",
        "Crestwell Validation Documentation",
    ],
    "Duratec Industrial": [
        "Duratec Industrial Gearboxes",
        "Duratec Shaft & Coupling Assemblies",
        "Duratec Bearing Housings",
        "Duratec Planetary Gear Sets",
        "Duratec Gearbox Rebuild Service",
        "Duratec Custom Drive Solutions",
    ],
    "Blackridge Works": [
        "Blackridge Structural Fabrication",
        "Blackridge Bridge Components",
        "Blackridge Heavy Weldments",
        "Blackridge Crane & Hoist Parts",
        "Blackridge Load Testing",
        "Blackridge On-Site Erection",
        "Blackridge AWS D1.1 Certified Welding",
    ],
    "Steelpath Manufacturing": [
        "Steelpath Railway Track Components",
        "Steelpath Switch & Crossing Parts",
        "Steelpath Rail Fastening Systems",
        "Steelpath Rolling Stock Parts",
        "Steelpath Quality Assurance Service",
        "Steelpath Custom Rail Fabrication",
    ],
    "Axiom Fabrication": [
        "Axiom Precision Sheet Metal",
        "Axiom Laser & Waterjet Cutting",
        "Axiom Welded Frames",
        "Axiom Electronic Enclosures",
        "Axiom Rack & Panel Builds",
        "Axiom Finishing & Plating",
        "Axiom Turnkey Sub-Assembly",
    ],
    "Orion Industrial": [
        "Orion Pump & Valve Components",
        "Orion Fluid Power Parts",
        "Orion Manifold Machining",
        "Orion Hydraulic Cylinder Assembly",
        "Orion Seal Groove Finishing",
        "Orion Pressure-Tested Assemblies",
    ],
    "Terranova Works": [
        "Terranova Earth-Moving Parts",
        "Terranova Ground Engagement Tools",
        "Terranova Bucket Teeth & Adapters",
        "Terranova Dozer Blade Components",
        "Terranova Wear Liner Kits",
        "Terranova OEM Replacement Parts",
        "Terranova Field Repair Service",
    ],
    "Coldforge Corp.": [
        "Coldforge Cold-Forged Fasteners",
        "Coldforge Cold-Headed Blanks",
        "Coldforge Net-Shape Parts",
        "Coldforge Thread Rolling",
        "Coldforge Drawn Tube & Rod",
        "Coldforge Surface Plating",
    ],
    "Harvestline Manufacturing": [
        "Harvestline Agricultural Equipment Parts",
        "Harvestline Combine Components",
        "Harvestline Planter Row Units",
        "Harvestline Grain Handling Parts",
        "Harvestline Season Prep Kits",
        "Harvestline Custom Farm Fab",
        "Harvestline OEM Replacement Inventory",
    ],
    "Riverton Tooling": [
        "Riverton Punch & Die Sets",
        "Riverton Special-Form Tooling",
        "Riverton Precision Boring Bars",
        "Riverton Custom Reamers",
        "Riverton Form Taps",
        "Riverton Regrind & Reconditioning",
        "Riverton Tool Steel Supply",
    ],
    "Bastion Machining": [
        "Bastion Defense Machined Parts",
        "Bastion Armor Component Fabrication",
        "Bastion Ballistic Test Parts",
        "Bastion ITAR Registered Manufacturing",
        "Bastion Mil-Spec Surface Finishing",
        "Bastion First Article & PPAP",
    ],
    "Ironvault Corp.": [
        "Ironvault Secure Cabinet Fabrication",
        "Ironvault Safe & Vault Doors",
        "Ironvault Armored Enclosures",
        "Ironvault Custom Lock Mechanism",
        "Ironvault Fire-Rated Storage",
        "Ironvault Field Installation & Service",
    ],
    "Stormgate Works": [
        "Stormgate Industrial Gate Fabrication",
        "Stormgate Security Barriers",
        "Stormgate Blast-Resistant Doors",
        "Stormgate Access Control Hardware",
        "Stormgate Custom Steel Doors",
        "Stormgate On-Site Installation",
    ],
    "Thornfield Manufacturing": [
        "Thornfield Precision Agricultural Parts",
        "Thornfield Seed Drill Components",
        "Thornfield Fertilizer Spreader Parts",
        "Thornfield Sprayer Boom Sections",
        "Thornfield Custom Farm Equipment",
        "Thornfield Seasonal MRO Kits",
        "Thornfield Welding & Repair Service",
    ],
    "Velox Industrial": [
        "Velox High-Speed Machined Parts",
        "Velox Automated Production Cells",
        "Velox Lights-Out Manufacturing Service",
        "Velox Robotic Grinding & Deburring",
        "Velox Rapid Prototype to Production",
        "Velox On-Time Delivery Program",
        "Velox Digital Quality Dashboard",
    ],
}


COMPANY_PRODUCT_DF = pd.DataFrame(COMPANY_PRODUCTS.items(), columns=["company", "product"]).explode(
    "product"
)
