COST_CENTERS = [
    "CC-1001 – Corporate Strategy & Planning",
    "CC-1002 – Executive Leadership Office",
    "CC-1003 – Legal & Compliance",
    "CC-1004 – Internal Audit",
    "CC-1005 – Risk Management",
    "CC-1006 – Human Resources – Recruiting",
    "CC-1007 – Human Resources – Benefits & Compensation",
    "CC-1008 – Human Resources – Learning & Development",
    "CC-1009 – Finance – Accounts Payable",
    "CC-1010 – Finance – Accounts Receivable",
    "CC-1011 – Finance – FP&A",
    "CC-1012 – Finance – Tax & Treasury",
    "CC-1013 – IT Infrastructure",
    "CC-1014 – IT Security & Compliance",
    "CC-1015 – IT – Software Engineering",
    "CC-1016 – IT – Data Engineering",
    "CC-1017 – IT – Enterprise Applications",
    "CC-1018 – Marketing – Brand & Communications",
    "CC-1019 – Marketing – Demand Generation",
    "CC-1020 – Marketing – Product Marketing",
    "CC-1021 – Marketing – Events & Partnerships",
    "CC-1022 – Sales – North America Enterprise",
    "CC-1023 – Sales – North America SMB",
    "CC-1024 – Sales – EMEA",
    "CC-1025 – Sales – APAC",
    "CC-1026 – Sales Operations & Enablement",
    "CC-1027 – Customer Success – Onboarding",
    "CC-1028 – Customer Success – Renewals",
    "CC-1029 – Customer Support – Tier 1",
    "CC-1030 – Customer Support – Tier 2 & Escalations",
    "CC-1031 – Product Management",
    "CC-1032 – UX & Design",
    "CC-1033 – Research & Development",
    "CC-1034 – Operations – Supply Chain",
    "CC-1035 – Operations – Facilities & Real Estate",
    "CC-1036 – Operations – Procurement",
    "CC-1037 – Operations – Office Administration",
    "CC-1038 – Business Intelligence & Analytics",
    "CC-1039 – Corporate Development & M&A",
    "CC-1040 – Sustainability & ESG Initiatives",
]
