# (iso2_code, country_name, gdp_usd_trillions)
# Ordered by GDP descending; gdp_usd_trillions used for weighted sampling in field generators
COUNTRIES = [
    ("US", "United States", 27.4),
    ("CN", "China", 17.7),
    ("DE", "Germany", 4.5),
    ("JP", "Japan", 4.2),
    ("IN", "India", 3.7),
    ("GB", "United Kingdom", 3.1),
    ("FR", "France", 3.0),
    ("BR", "Brazil", 2.1),
    ("IT", "Italy", 2.1),
    ("CA", "Canada", 2.1),
    ("RU", "Russia", 1.9),
    ("MX", "Mexico", 1.8),
    ("KR", "South Korea", 1.7),
    ("AU", "Australia", 1.7),
    ("ES", "Spain", 1.6),
    ("ID", "Indonesia", 1.4),
    ("NL", "Netherlands", 1.1),
    ("TR", "Turkey", 1.1),
    ("SA", "Saudi Arabia", 1.1),
    ("CH", "Switzerland", 0.9),
    ("PL", "Poland", 0.8),
    ("BE", "Belgium", 0.6),
    ("SE", "Sweden", 0.6),
    ("AR", "Argentina", 0.6),
    ("NO", "Norway", 0.6),
    ("AT", "Austria", 0.5),
    ("AE", "United Arab Emirates", 0.5),
    ("SG", "Singapore", 0.5),
    ("IL", "Israel", 0.5),
    ("NG", "Nigeria", 0.5),
    ("TH", "Thailand", 0.5),
    ("ZA", "South Africa", 0.4),
    ("MY", "Malaysia", 0.4),
    ("DK", "Denmark", 0.4),
    ("PH", "Philippines", 0.4),
    ("VN", "Vietnam", 0.4),
    ("EG", "Egypt", 0.4),
    ("CL", "Chile", 0.3),
    ("CZ", "Czech Republic", 0.3),
    ("CO", "Colombia", 0.3),
    ("FI", "Finland", 0.3),
    ("PT", "Portugal", 0.3),
    ("RO", "Romania", 0.3),
    ("PK", "Pakistan", 0.3),
    ("HU", "Hungary", 0.2),
    ("NZ", "New Zealand", 0.2),
    ("KE", "Kenya", 0.1),
]
