STREET_NAMES = [
    # Original
    "Main Street",
    "First Avenue",
    "Oak Boulevard",
    "Elm Street",
    "Maple Avenue",
    "Cedar Lane",
    "Commerce Drive",
    "Industrial Parkway",
    "Harbor Boulevard",
    "Technology Way",
    "Enterprise Avenue",
    "Market Street",
    "River Road",
    "Park Avenue",
    "Grand Boulevard",
    "Central Avenue",
    "Business Center Drive",
    "Innovation Drive",
    "Trade Center Boulevard",
    "Gateway Drive",
    # Additional
    "Willow Court",
    "Pine Street",
    "Birch Road",
    "Spruce Avenue",
    "Magnolia Drive",
    "Sycamore Lane",
    "Chestnut Street",
    "Poplar Boulevard",
    "Walnut Avenue",
    "Ash Court",
    "Summit Road",
    "Valley View Drive",
    "Hillcrest Avenue",
    "Ridge Road",
    "Lakeside Drive",
    "Meadow Lane",
    "Sunset Boulevard",
    "Sunrise Court",
    "Creekside Drive",
    "Brookside Avenue",
    "Riverside Drive",
    "Bayview Boulevard",
    "Oceanfront Drive",
    "Cliffside Road",
    "Woodland Way",
    "Forest Lane",
    "Greenway Boulevard",
    "Prairie Road",
    "Frontier Drive",
    "Heritage Avenue",
    "Colonial Road",
    "Liberty Street",
    "Freedom Boulevard",
    "Constitution Avenue",
    "Independence Drive",
    "Corporate Plaza",
    "Executive Parkway",
    "Logistics Drive",
    "Warehouse Row",
    "Distribution Center Road",
    "Manufacturing Way",
    "Supply Chain Boulevard",
    "Freight Terminal Drive",
    "Commerce Park Road",
    "Capital Boulevard",
    "Financial Center Drive",
    "Exchange Place",
    "Merchant Square",
    "Traders Lane",
    "Industrial Court",
]
