COMPANY_USER_EMAILS = [
    # Arcoven Systems
    "alex.chen@arcovensystems.com",
    "jordan.patel@arcovensystems.com",
    "taylor.williams@arcovensystems.com",
    "morgan.johnson@arcovensystems.com",
    "casey.brown@arcovensystems.com",
    # Nexlith AI
    "riley.davis@nexlithai.com",
    "avery.miller@nexlithai.com",
    "jamie.wilson@nexlithai.com",
    "quinn.moore@nexlithai.com",
    "blake.taylor@nexlithai.com",
    # Qubit Foundry
    "cameron.anderson@qubitfoundry.com",
    "drew.thomas@qubitfoundry.com",
    "skyler.jackson@qubitfoundry.com",
    "rowan.white@qubitfoundry.com",
    "sage.harris@qubitfoundry.com",
    # Solvera Labs
    "reese.martin@solveralabs.com",
    "logan.thompson@solveralabs.com",
    "parker.garcia@solveralabs.com",
    "hayden.martinez@solveralabs.com",
    "finley.robinson@solveralabs.com",
    # Vantiq Cloud
    "emery.clark@vantiqcloud.com",
    "dakota.rodriguez@vantiqcloud.com",
    "charlie.lewis@vantiqcloud.com",
    "adrian.lee@vantiqcloud.com",
    "alexis.walker@vantiqcloud.com",
    # Creston Data
    "brooke.hall@crestondata.com",
    "caden.allen@crestondata.com",
    "diana.young@crestondata.com",
    "elena.hernandez@crestondata.com",
    "felix.king@crestondata.com",
    # Novalume Inc.
    "grace.wright@novalume.com",
    "hunter.lopez@novalume.com",
    "iris.hill@novalume.com",
    "jason.scott@novalume.com",
    "kayla.green@novalume.com",
    # Phalanx Security
    "liam.adams@phalanxsecurity.com",
    "maya.baker@phalanxsecurity.com",
    "noah.gonzalez@phalanxsecurity.com",
    "olivia.nelson@phalanxsecurity.com",
    "piper.carter@phalanxsecurity.com",
    # Runecode Corp.
    "rachel.mitchell@runecode.com",
    "samuel.perez@runecode.com",
    "tara.roberts@runecode.com",
    "uma.turner@runecode.com",
    "victor.phillips@runecode.com",
    # Tessact Software
    "willow.campbell@tessactsoftware.com",
    "xavier.parker@tessactsoftware.com",
    "yasmine.evans@tessactsoftware.com",
    "zoe.edwards@tessactsoftware.com",
    "aaron.collins@tessactsoftware.com",
    # Lyrion Networks
    "bella.stewart@lyrionnetworks.com",
    "connor.sanchez@lyrionnetworks.com",
    "daisy.morris@lyrionnetworks.com",
    "ethan.rogers@lyrionnetworks.com",
    "fiona.reed@lyrionnetworks.com",
    # Obsidia Tech
    "gavin.cook@obsidiatech.com",
    "hannah.morgan@obsidiatech.com",
    "ivan.bell@obsidiatech.com",
    "julia.murphy@obsidiatech.com",
    "kevin.bailey@obsidiatech.com",
    # Pulsar Compute
    "lily.rivera@pulsarcompute.com",
    "mason.cooper@pulsarcompute.com",
    "nora.richardson@pulsarcompute.com",
    "owen.cox@pulsarcompute.com",
    "paige.howard@pulsarcompute.com",
    # Driftware
    "ryan.ward@driftware.com",
    "sofia.torres@driftware.com",
    "tyler.peterson@driftware.com",
    "ursula.gray@driftware.com",
    "violet.ramirez@driftware.com",
    # Intrium Digital
    "wesley.james@intriumdigital.com",
    "xena.watson@intriumdigital.com",
    "yara.brooks@intriumdigital.com",
    "zach.kelly@intriumdigital.com",
    "amber.sanders@intriumdigital.com",
    # Coda Robotics
    "brian.price@codarobotics.com",
    "claire.bennett@codarobotics.com",
    "derek.wood@codarobotics.com",
    "eva.barnes@codarobotics.com",
    "frank.ross@codarobotics.com",
    # Veratex AI
    "gina.henderson@veratexai.com",
    "henry.coleman@veratexai.com",
    "isa.jenkins@veratexai.com",
    "jake.perry@veratexai.com",
    "karen.powell@veratexai.com",
    # Spectra Logic
    "luke.long@spectralogic.com",
    "mia.patterson@spectralogic.com",
    "nathan.hughes@spectralogic.com",
    "ophelia.flores@spectralogic.com",
    "peter.washington@spectralogic.com",
    # Kinetica Systems
    "queenie.butler@kineticasystems.com",
    "rosa.simmons@kineticasystems.com",
    "steve.foster@kineticasystems.com",
    "tina.gonzales@kineticasystems.com",
    "ulric.bryant@kineticasystems.com",
    # Zephyr Compute
    "vera.alexander@zephyrcompute.com",
    "walter.russell@zephyrcompute.com",
    "xiao.griffin@zephyrcompute.com",
    "yuki.diaz@zephyrcompute.com",
    "zara.hayes@zephyrcompute.com",
    # Cargolux Direct
    "alex.myers@cargoluxdirect.com",
    "jordan.ford@cargoluxdirect.com",
    "taylor.hamilton@cargoluxdirect.com",
    "morgan.graham@cargoluxdirect.com",
    "casey.sullivan@cargoluxdirect.com",
    # Pathvex Freight
    "riley.wallace@pathvexfreight.com",
    "avery.woods@pathvexfreight.com",
    "jamie.cole@pathvexfreight.com",
    "quinn.west@pathvexfreight.com",
    "blake.jordan@pathvexfreight.com",
    # Ironline Shipping
    "cameron.owens@ironlineshipping.com",
    "drew.reynolds@ironlineshipping.com",
    "skyler.fisher@ironlineshipping.com",
    "rowan.ellis@ironlineshipping.com",
    "sage.harrison@ironlineshipping.com",
    # Deckway Logistics
    "reese.gibson@deckwaylogistics.com",
    "logan.mcdonald@deckwaylogistics.com",
    "parker.cruz@deckwaylogistics.com",
    "hayden.marshall@deckwaylogistics.com",
    "finley.ortiz@deckwaylogistics.com",
    # Surebound Courier
    "emery.gomez@sureboundcourier.com",
    "dakota.murray@sureboundcourier.com",
    "charlie.freeman@sureboundcourier.com",
    "adrian.wells@sureboundcourier.com",
    "alexis.webb@sureboundcourier.com",
    # Coldrun Transport
    "brooke.simpson@coldruntransport.com",
    "caden.stevens@coldruntransport.com",
    "diana.tucker@coldruntransport.com",
    "elena.porter@coldruntransport.com",
    "felix.hunter@coldruntransport.com",
    # Waymark Supply
    "grace.hicks@waymarksupply.com",
    "hunter.crawford@waymarksupply.com",
    "iris.henry@waymarksupply.com",
    "jason.boyd@waymarksupply.com",
    "kayla.mason@waymarksupply.com",
    # Portside Group
    "liam.morales@portsidegroup.com",
    "maya.kennedy@portsidegroup.com",
    "noah.warren@portsidegroup.com",
    "olivia.dixon@portsidegroup.com",
    "piper.ramos@portsidegroup.com",
    # Clearspan Freight
    "rachel.reyes@clearspanfreight.com",
    "samuel.burns@clearspanfreight.com",
    "tara.gordon@clearspanfreight.com",
    "uma.shaw@clearspanfreight.com",
    "victor.holmes@clearspanfreight.com",
    # Orion Fulfillment
    "willow.rice@orionfulfillment.com",
    "xavier.robertson@orionfulfillment.com",
    "yasmine.hunt@orionfulfillment.com",
    "zoe.black@orionfulfillment.com",
    "aaron.daniels@orionfulfillment.com",
    # Corevast Materials
    "bella.palmer@corevastmaterials.com",
    "connor.mills@corevastmaterials.com",
    "daisy.nichols@corevastmaterials.com",
    "ethan.grant@corevastmaterials.com",
    "fiona.knight@corevastmaterials.com",
    # Ironveil Industries
    "gavin.ferguson@ironveilindustries.com",
    "hannah.rose@ironveilindustries.com",
    "ivan.stone@ironveilindustries.com",
    "julia.hawkins@ironveilindustries.com",
    "kevin.dunn@ironveilindustries.com",
    # Densium Corp.
    "lily.perkins@densium.com",
    "mason.hudson@densium.com",
    "nora.spencer@densium.com",
    "owen.gardner@densium.com",
    "paige.stephens@densium.com",
    # Ferrovance Ltd.
    "ryan.payne@ferrovance.com",
    "sofia.pierce@ferrovance.com",
    "tyler.berry@ferrovance.com",
    "ursula.matthews@ferrovance.com",
    "violet.arnold@ferrovance.com",
    # Caldera Minerals
    "wesley.wagner@calderaminerals.com",
    "xena.willis@calderaminerals.com",
    "yara.ray@calderaminerals.com",
    "zach.watkins@calderaminerals.com",
    "amber.olson@calderaminerals.com",
    # Carbide Works
    "brian.carroll@carbideworks.com",
    "claire.duncan@carbideworks.com",
    "derek.snyder@carbideworks.com",
    "eva.hart@carbideworks.com",
    "frank.cunningham@carbideworks.com",
    # Steelbrook Group
    "gina.bradley@steelbrookgroup.com",
    "henry.lane@steelbrookgroup.com",
    "isa.andrews@steelbrookgroup.com",
    "jake.ruiz@steelbrookgroup.com",
    "karen.harper@steelbrookgroup.com",
    # Graphene One
    "luke.fox@grapheneone.com",
    "mia.riley@grapheneone.com",
    "nathan.armstrong@grapheneone.com",
    "ophelia.carpenter@grapheneone.com",
    "peter.weaver@grapheneone.com",
    # Luminary Studios
    "queenie.greene@luminarystudios.com",
    "rosa.lawrence@luminarystudios.com",
    "steve.elliott@luminarystudios.com",
    "tina.chavez@luminarystudios.com",
    "ulric.sims@luminarystudios.com",
    # Echoplex Media
    "vera.austin@echoplexmedia.com",
    "walter.peters@echoplexmedia.com",
    "xiao.kelley@echoplexmedia.com",
    "yuki.franklin@echoplexmedia.com",
    "zara.lawson@echoplexmedia.com",
    # Prism Pictures
    "alex.fields@prismpictures.com",
    "jordan.gutierrez@prismpictures.com",
    "taylor.ryan@prismpictures.com",
    "morgan.schmidt@prismpictures.com",
    "casey.carr@prismpictures.com",
    # Nightfall Games
    "riley.vasquez@nightfallgames.com",
    "avery.castillo@nightfallgames.com",
    "jamie.wheeler@nightfallgames.com",
    "quinn.chapman@nightfallgames.com",
    "blake.oliver@nightfallgames.com",
    # Starfield Studios
    "cameron.montgomery@starfieldstudios.com",
    "drew.richards@starfieldstudios.com",
    "skyler.williamson@starfieldstudios.com",
    "rowan.johnston@starfieldstudios.com",
    "sage.banks@starfieldstudios.com",
    # Resonant Audio
    "reese.meyer@resonantaudio.com",
    "logan.bishop@resonantaudio.com",
    "parker.mccoy@resonantaudio.com",
    "hayden.howell@resonantaudio.com",
    "finley.alvarez@resonantaudio.com",
    # Canopy Creative
    "emery.morrison@canopycreative.com",
    "dakota.hansen@canopycreative.com",
    "charlie.fernandez@canopycreative.com",
    "adrian.garza@canopycreative.com",
    "alexis.harvey@canopycreative.com",
    # Ironwood Pictures
    "brooke.little@ironwoodpictures.com",
    "caden.burton@ironwoodpictures.com",
    "diana.stanley@ironwoodpictures.com",
    "elena.nguyen@ironwoodpictures.com",
    "felix.george@ironwoodpictures.com",
    # Aurum Capital
    "grace.jacobs@aurumcapital.com",
    "hunter.reid@aurumcapital.com",
    "iris.kim@aurumcapital.com",
    "jason.norris@aurumcapital.com",
    "kayla.medina@aurumcapital.com",
    # Vantage Equity
    "liam.aguilar@vantageequity.com",
    "maya.dennis@vantageequity.com",
    "noah.sutton@vantageequity.com",
    "olivia.wade@vantageequity.com",
    "piper.graves@vantageequity.com",
    # Halcyon Funds
    "rachel.haynes@halcyonfunds.com",
    "samuel.garner@halcyonfunds.com",
    "tara.walton@halcyonfunds.com",
    "uma.munoz@halcyonfunds.com",
    "victor.davidson@halcyonfunds.com",
    # Stratum Capital
    "willow.norris@stratumcapital.com",
    "xavier.sutton@stratumcapital.com",
    "yasmine.wade@stratumcapital.com",
    "zoe.graves@stratumcapital.com",
    "aaron.haynes@stratumcapital.com",
    # Clearview Advisors
    "bella.garner@clearviewadvisors.com",
    "connor.walton@clearviewadvisors.com",
    "daisy.munoz@clearviewadvisors.com",
    "ethan.davidson@clearviewadvisors.com",
    "fiona.norris@clearviewadvisors.com",
    # Greystone Equity
    "gavin.huang@greystoneequity.com",
    "hannah.okafor@greystoneequity.com",
    "ivan.vasquez@greystoneequity.com",
    "julia.johansson@greystoneequity.com",
    "kevin.nguyen@greystoneequity.com",
    # Tidewater Capital
    "lily.sharma@tidewatercapital.com",
    "mason.obrien@tidewatercapital.com",
    "nora.kowalski@tidewatercapital.com",
    "owen.petrov@tidewatercapital.com",
    "paige.ibrahim@tidewatercapital.com",
    # Ironclad Fabrication
    "ryan.anderson@ironcladfabrication.com",
    "sofia.thomas@ironcladfabrication.com",
    "tyler.jackson@ironcladfabrication.com",
    "ursula.white@ironcladfabrication.com",
    "violet.harris@ironcladfabrication.com",
    # Vortex Industrial
    "wesley.martin@vortexindustrial.com",
    "xena.thompson@vortexindustrial.com",
    "yara.garcia@vortexindustrial.com",
    "zach.martinez@vortexindustrial.com",
    "amber.robinson@vortexindustrial.com",
    # Apex Machining
    "brian.clark@apexmachining.com",
    "claire.rodriguez@apexmachining.com",
    "derek.lewis@apexmachining.com",
    "eva.lee@apexmachining.com",
    "frank.walker@apexmachining.com",
    # Tekton Works
    "gina.hall@tektonworks.com",
    "henry.allen@tektonworks.com",
    "isa.young@tektonworks.com",
    "jake.hernandez@tektonworks.com",
    "karen.king@tektonworks.com",
    # Forgemaster Inc.
    "luke.wright@forgemaster.com",
    "mia.lopez@forgemaster.com",
    "nathan.hill@forgemaster.com",
    "ophelia.scott@forgemaster.com",
    "peter.green@forgemaster.com",
    # Halcyon Precision
    "queenie.adams@halcyonprecision.com",
    "rosa.baker@halcyonprecision.com",
    "steve.gonzalez@halcyonprecision.com",
    "tina.nelson@halcyonprecision.com",
    "ulric.carter@halcyonprecision.com",
    # Stratum Industrial
    "vera.mitchell@stratumindustrial.com",
    "walter.perez@stratumindustrial.com",
    "xiao.roberts@stratumindustrial.com",
    "yuki.turner@stratumindustrial.com",
    "zara.phillips@stratumindustrial.com",
]
